In [64]:
import pandas as pd
import numpy as np

In [65]:
la3 = pd.read_csv('property.csv')
la3.head(5)

Title_URL  Content  Content1  \
0           \n12 Bedroom Office\n        1         4   
1  \n3 Bedroom Flat & Apartment\n        1         4   
2            \n4 Bedroom Duplex\n        1         4   
3            \n4 Bedroom Duplex\n        1         4   
4            \n4 Bedroom Duplex\n        1         4   

                                                item Image Image2 Image3  \
0  \n*Newly Renovated and Very Spacious 4 Numbers...   NaN    NaN    NaN   
1  \nSpacious and beautifully finished and furnis...   NaN    NaN    NaN   
2  \n4 bedroom semi detached, fully detached hous...   NaN    NaN    NaN   
3  \nNewly built 4 Bedroom Semi- detached duplex,...   NaN    NaN    NaN   
4  \nWELL FINISHE FOUR BEDROOM DUPLEX WITH 2 ROOM...   NaN    NaN    NaN   

                                           Price_URL  \
0  https://www.privateproperty.com.ng/listings/12...   
1  https://www.privateproperty.com.ng/listings/3-...   
2  https://www.privateproperty.com.ng/listings/4-...   
3  https://www.privateproperty.com.ng/listings/4-...   
4  https://www.privateproperty.com.ng/listings/4-...   

                      Price  hbeds  hbaths  hgarage  \
0  N10,800,000,000 per year   12.0    12.0      NaN   
1       N9,000,000 per year    3.0     2.0      NaN   
2       N3,500,000 per year    4.0     4.0      3.0   
3       N3,600,000 per year    4.0     4.0      2.0   
4       N4,500,000 per year    4.0     4.0      NaN   

                                    propertylocation  \
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...   
1                             Club Road Ikoyi, Ikoyi   
2                     Roxby Homes, Vgc, Ikota, Lekki   
3             2Nd Toll Gate, Lekki Expressway, Lekki   
4            Victoria Arubieke, Lekki Phase 1, Lekki   

                                             Address  \
0         Newly Renovated 4 Units of 3 Bedroom Flats   
1   Furnished 3 bedroom Flat and apartment for le...   
2                 4 BEDROOM DETACHED DUPLEX FOR RENT   
3   Newly Built 4 Bedroom Semi - Detached Duplex ...   
4   TASTEFULLY FINISHED FOUR BEDROOM DUPLEX WITH ...   

                                            Info_URL Image4  
0  https://www.privateproperty.com.ng/estate-agen...    NaN  
1  https://www.privateproperty.com.ng/estate-agen...    NaN  
2  https://www.privateproperty.com.ng/estate-agen...    NaN  
3  https://www.privateproperty.com.ng/estate-agen...    NaN  
4  https://www.privateproperty.com.ng/estate-agen...    NaN

In [66]:
la3 = la3.drop(['Image', 'Image2', 'Image3', 'Price_URL', 'Info_URL', 'Image4'], axis = 'columns')

In [67]:
la3.head(3)

Title_URL  Content  Content1  \
0           \n12 Bedroom Office\n        1         4   
1  \n3 Bedroom Flat & Apartment\n        1         4   
2            \n4 Bedroom Duplex\n        1         4   

                                                item  \
0  \n*Newly Renovated and Very Spacious 4 Numbers...   
1  \nSpacious and beautifully finished and furnis...   
2  \n4 bedroom semi detached, fully detached hous...   

                      Price  hbeds  hbaths  hgarage  \
0  N10,800,000,000 per year   12.0    12.0      NaN   
1       N9,000,000 per year    3.0     2.0      NaN   
2       N3,500,000 per year    4.0     4.0      3.0   

                                    propertylocation  \
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...   
1                             Club Road Ikoyi, Ikoyi   
2                     Roxby Homes, Vgc, Ikota, Lekki   

                                             Address  
0         Newly Renovated 4 Units of 3 Bedroom Flats  
1   Furnished 3 bedroom Flat and apartment for le...  
2                 4 BEDROOM DETACHED DUPLEX FOR RENT

In [68]:
la3 = la3.drop(['Content', 'Content1'], axis = 'columns')

In [69]:
la3 = la3.drop(['item', 'hgarage', 'Address'], axis = 'columns')

In [70]:
la3.head()

Title_URL                     Price  hbeds  hbaths  \
0           \n12 Bedroom Office\n  N10,800,000,000 per year   12.0    12.0   
1  \n3 Bedroom Flat & Apartment\n       N9,000,000 per year    3.0     2.0   
2            \n4 Bedroom Duplex\n       N3,500,000 per year    4.0     4.0   
3            \n4 Bedroom Duplex\n       N3,600,000 per year    4.0     4.0   
4            \n4 Bedroom Duplex\n       N4,500,000 per year    4.0     4.0   

                                    propertylocation  
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...  
1                             Club Road Ikoyi, Ikoyi  
2                     Roxby Homes, Vgc, Ikota, Lekki  
3             2Nd Toll Gate, Lekki Expressway, Lekki  
4            Victoria Arubieke, Lekki Phase 1, Lekki

In [71]:
la3[['Title', 'Price', 'Location', 'Beds', 'Baths']] = la3[['Title_URL', 'Price', 'propertylocation','hbeds','hbaths']]

In [72]:
la3.head(3)

Title_URL                     Price  hbeds  hbaths  \
0           \n12 Bedroom Office\n  N10,800,000,000 per year   12.0    12.0   
1  \n3 Bedroom Flat & Apartment\n       N9,000,000 per year    3.0     2.0   
2            \n4 Bedroom Duplex\n       N3,500,000 per year    4.0     4.0   

                                    propertylocation  \
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...   
1                             Club Road Ikoyi, Ikoyi   
2                     Roxby Homes, Vgc, Ikota, Lekki   

                            Title  \
0           \n12 Bedroom Office\n   
1  \n3 Bedroom Flat & Apartment\n   
2            \n4 Bedroom Duplex\n   

                                            Location  Beds  Baths  
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...  12.0   12.0  
1                             Club Road Ikoyi, Ikoyi   3.0    2.0  
2                     Roxby Homes, Vgc, Ikota, Lekki   4.0    4.0

In [73]:
la3 = la3.drop(['Title_URL', 'propertylocation','hbeds','hbaths'], axis = 'columns')

In [74]:
la3.head(3)

Price                           Title  \
0  N10,800,000,000 per year           \n12 Bedroom Office\n   
1       N9,000,000 per year  \n3 Bedroom Flat & Apartment\n   
2       N3,500,000 per year            \n4 Bedroom Duplex\n   

                                            Location  Beds  Baths  
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...  12.0   12.0  
1                             Club Road Ikoyi, Ikoyi   3.0    2.0  
2                     Roxby Homes, Vgc, Ikota, Lekki   4.0    4.0

In [75]:
la3.isna().sum()

Price       0
Title       0
Location    0
Beds        2
Baths       2
dtype: int64

In [76]:
la3[la3['Beds'].isna()]

Price       Title  \
23        N95,000 per year  \nOffice\n   
180  N250,000,000 per year   \nHotel\n   

                                    Location  Beds  Baths  
23                           Victoria Island   NaN    NaN  
180    Off Allen Avenue, Allen Avenue, Ikeja   NaN    NaN

In [77]:
la3 = la3.dropna()

In [78]:
la3.isna().sum()

Price       0
Title       0
Location    0
Beds        0
Baths       0
dtype: int64

In [79]:
la3['Title'].unique()

array(['\n12 Bedroom Office\n', '\n3 Bedroom Flat & Apartment\n',
       '\n4 Bedroom Duplex\n', '\n4 Bedroom Townhouse\n',
       '\n3 Bedroom Townhouse\n', '\n3 Bedroom Terrace\n',
       '\n2 Bedroom Flat & Apartment\n', '\n4 Bedroom Flat & Apartment\n',
       '\n2 Bedroom Duplex\n', '\n5 Bedroom Duplex\n',
       '\n5 Bedroom House\n', '\n4 Bedroom Terrace\n',
       '\n3 Bedroom Duplex\n', '\n5 Bedroom Terrace\n',
       '\n4 Bedroom Duplex\n ', '\n4 Bedroom House\n',
       '\n3500000 Bedroom Duplex\n', '\n4 Bedroom Bungalow\n',
       '\n3 Bedroom House\n', '\n 4 Bedroom Terrace\n',
       '\n 4 Bedroom Duplex\n'], dtype=object)

In [80]:
la3['Price'].unique()

array(['N10,800,000,000 per year', 'N9,000,000 per year',
       'N3,500,000 per year', 'N3,600,000 per year',
       'N4,500,000 per year', 'N5,500,000 per year',
       'N6,000,000 per year', 'N8,000,000 per year',
       'N2,500,000 per year', 'N15,000,000 per year',
       'N3,000,000 per year', 'N2,000,000 per year',
       'N4,200,000 per year', 'N25,000,000 per year',
       'N3,200,000 per year', 'N5,000,000 per year',
       'N2,750,000 per year', 'N3,800,000 per year',
       'N4,000,000 per year', 'N22,000,000 per year',
       'N16,000,000 per year', 'N600,000 per year',
       'N12,000,000 per year', 'N1,000,000 per year',
       'N1,100,000 per year', 'N6,500,000 per year',
       'N2,200,000 per year', 'N10,000,000 per year',
       'N1,600,000 per year', 'N1,640,000 per year',
       'N3,700,000 per year', 'N35,000,000 per year',
       'N7,000,000 per year', 'N13,000,000 per year',
       'N24,000,000 per year', 'N3,300,000 per year',
       'N55,000,000 per year', 'N2

In [81]:
def price(x):
    a = x.split()
    b = a[0]
    c = b.split(',')
    d = ''
    for i in range(len(c)):
        d += c[i]
    e = list(d)[1:]
    f =''
    for i in range(len(e)):
        f += e[i]
    return f

In [82]:
price('N2,700,000 per year')

'2700000'

In [83]:
la3['Price'] = la3['Price'].apply(price)

In [84]:
la3['Price'].unique()

array(['10800000000', '9000000', '3500000', '3600000', '4500000',
       '5500000', '6000000', '8000000', '2500000', '15000000', '3000000',
       '2000000', '4200000', '25000000', '3200000', '5000000', '2750000',
       '3800000', '4000000', '22000000', '16000000', '600000', '12000000',
       '1000000', '1100000', '6500000', '2200000', '10000000', '1600000',
       '1640000', '3700000', '35000000', '7000000', '13000000',
       '24000000', '3300000', '55000000', '2800000', '2600000', '2300000',
       '700000', '1300000', '900000', '2700000', '1500000'], dtype=object)

In [85]:
la3.head(5)

Price                           Title  \
0  10800000000           \n12 Bedroom Office\n   
1      9000000  \n3 Bedroom Flat & Apartment\n   
2      3500000            \n4 Bedroom Duplex\n   
3      3600000            \n4 Bedroom Duplex\n   
4      4500000            \n4 Bedroom Duplex\n   

                                            Location  Beds  Baths  
0    Town Planning Estate, Ilupeju, Lagos., Ilupe...  12.0   12.0  
1                             Club Road Ikoyi, Ikoyi   3.0    2.0  
2                     Roxby Homes, Vgc, Ikota, Lekki   4.0    4.0  
3             2Nd Toll Gate, Lekki Expressway, Lekki   4.0    4.0  
4            Victoria Arubieke, Lekki Phase 1, Lekki   4.0    4.0

In [86]:
la3['Location'].unique()

array(['  Town Planning Estate, Ilupeju, Lagos., Ilupeju, Ikorodu Road',
       '  Club Road Ikoyi, Ikoyi', '  Roxby Homes, Vgc, Ikota, Lekki',
       '  2Nd Toll Gate, Lekki Expressway, Lekki',
       '  Victoria Arubieke, Lekki Phase 1, Lekki',
       '  Off Audu Epkeka, Lekki Phase 1, Lekki',
       '  Ikate, Ikate Elegushi, Lekki', '  Ikoyi',
       '  Orchid Road, Lekki 2Nd Toll Gate, Lekki, Chevron Drive, Lekki',
       '  Ikota, Lekki', '  Old Ikoyi , Ikoyi',
       '  2Nd Toll Gate , Lekki Expressway, Lekki',
       '  Within Sangotedo Shop Rite , Sangotedo, Ajah',
       '  Westend Estate , Ikota, Lekki', '  Westend , Ikota, Lekki',
       '  Ocean Parade, Banana Island, Banana Island, Ikoyi',
       '  Banana Island Road, Banana Island, Ikoyi',
       '  Bode Thomas, Surulere', '  Ologolo, Lekki',
       '  Osapa London , Osapa, Lekki', '  Idado, Lekki',
       '  Osapa, Lekki', '  2Nd Toll Gate, Chevron Drive, Lekki',
       '  Kingsbay Estate , Ikota, Lekki',
       '  Osap

In [87]:
def locate_val(x):
    a = x.split(';')
    b = a[-1]
    c = b.split()
    return c[-1]

In [88]:
locate_val('Lekki County Estate , Ikota, Lekki')

'Lekki'

In [89]:
la3['Location'] = la3['Location'].apply(locate_val)

In [93]:
la3['Location'].unique()

array(['Road', 'Ikoyi', 'Lekki', 'Ajah', 'Surulere', 'Island', 'Ikeja'],
      dtype=object)

In [94]:
la3[la3['Location']== 'Island']

Price                           Title Location  Beds  Baths
65    3000000  \n2 Bedroom Flat & Apartment\n   Island   2.0    2.0
143   5000000           \n4 Bedroom Terrace\n   Island   4.0    5.0
154   4500000           \n4 Bedroom Terrace\n   Island   4.0    5.0
234   6000000  \n3 Bedroom Flat & Apartment\n   Island   3.0    3.0
238   3000000  \n2 Bedroom Flat & Apartment\n   Island   2.0    3.0
240   6000000  \n3 Bedroom Flat & Apartment\n   Island   3.0    4.0
245   3500000  \n3 Bedroom Flat & Apartment\n   Island   3.0    3.0
246   4000000  \n3 Bedroom Flat & Apartment\n   Island   3.0    4.0
247   3000000  \n3 Bedroom Flat & Apartment\n   Island   3.0    4.0
253   3500000  \n3 Bedroom Flat & Apartment\n   Island   3.0    3.0
269  10000000  \n3 Bedroom Flat & Apartment\n   Island   3.0    4.0

In [109]:
la3[la3['Location']== 'Road']

Price                  Title Location  Beds  Baths
0  10800000000  \n12 Bedroom Office\n     Road    12     12

In [110]:
la3.loc[0, 'Location'] = 'Ikorodu'

In [95]:
la3['Location'].unique()

array(['Road', 'Ikoyi', 'Lekki', 'Ajah', 'Surulere', 'Island', 'Ikeja'],
      dtype=object)

In [96]:
la3['Location'] = la3['Location'].apply(lambda x: 'Victoria Island' if x == 'Island' else x)

In [97]:
la3['Location'].unique()

array(['Road', 'Ikoyi', 'Lekki', 'Ajah', 'Surulere', 'Victoria Island',
       'Ikeja'], dtype=object)

In [98]:
la3['Beds'].unique()

array([1.2e+01, 3.0e+00, 4.0e+00, 2.0e+00, 5.0e+00, 3.5e+06])

In [99]:
la3['Beds']  = la3['Beds'].astype(int)

In [100]:
la3['Beds'].unique()

array([     12,       3,       4,       2,       5, 3500000])

In [101]:
la3[la3['Beds'] == 3500000]

Price                       Title Location     Beds  Baths
85  3500000  \n3500000 Bedroom Duplex\n    Lekki  3500000    4.0

In [103]:
la3.loc[85, 'Beds'] = 3

In [104]:
la3['Beds'].unique()

array([12,  3,  4,  2,  5])

In [106]:
la3['Baths'] = la3['Baths'].astype(int)

In [107]:
la3['Baths'].unique()

array([12,  2,  4,  3,  5,  6,  1,  8,  7])

In [111]:
la3.head()

Price                           Title Location  Beds  Baths
0  10800000000           \n12 Bedroom Office\n  Ikorodu    12     12
1      9000000  \n3 Bedroom Flat & Apartment\n    Ikoyi     3      2
2      3500000            \n4 Bedroom Duplex\n    Lekki     4      4
3      3600000            \n4 Bedroom Duplex\n    Lekki     4      4
4      4500000            \n4 Bedroom Duplex\n    Lekki     4      4

In [112]:
la3['Toilets'] = la3['Baths']

In [113]:
la3.head()

Price                           Title Location  Beds  Baths  Toilets
0  10800000000           \n12 Bedroom Office\n  Ikorodu    12     12       12
1      9000000  \n3 Bedroom Flat & Apartment\n    Ikoyi     3      2        2
2      3500000            \n4 Bedroom Duplex\n    Lekki     4      4        4
3      3600000            \n4 Bedroom Duplex\n    Lekki     4      4        4
4      4500000            \n4 Bedroom Duplex\n    Lekki     4      4        4

In [114]:
column_list = ['Title', 'Price', 'Location', 'Beds', 'Baths', 'Toilets']
la3 = la3.reindex(columns = column_list)

In [115]:
la3.head()

Title        Price Location  Beds  Baths  Toilets
0           \n12 Bedroom Office\n  10800000000  Ikorodu    12     12       12
1  \n3 Bedroom Flat & Apartment\n      9000000    Ikoyi     3      2        2
2            \n4 Bedroom Duplex\n      3500000    Lekki     4      4        4
3            \n4 Bedroom Duplex\n      3600000    Lekki     4      4        4
4            \n4 Bedroom Duplex\n      4500000    Lekki     4      4        4

In [116]:
la3.to_csv('la3.csv', index = False)